name: CD on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  delivery:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ソースコードのダウンロード
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: 依存関係のインストール
        run: npm ci

      - name: アプリケーションのビルド
        run: npm run build

      - name: GitHub Packages へのログイン
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Image のビルド
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Docker Image のアップロード
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
